(() => {
  'use strict';
  const PARTNER = 18772737;
  const TABLE = '3815';
  const PROXY = 'https://rgs--livedealerwebsocket-bcapps-org-betconstruct.betconstruct-proxy.duel.net';
  const H5 = { websocket:'wss://bintu-h5live.nanocosmos.de:443/h5live/stream/stream.mp4', hls:'https://bintu-h5live.nanocosmos.de:443/h5live/http/playlist.m3u8', progressive:'https://bintu-h5live.nanocosmos.de:443/h5live/http/stream.mp4' };
  let socket, player, guestSid='', controller='', userSid='', userNick='', chatHandle;
  const state = document.getElementById('videoState'), auth = document.getElementById('authState');
  const headers = extra => Object.assign({'Content-Type':'application/json; charset=utf-8','User-Agent':navigator.userAgent},extra||{});
  function command(method,params,query,data,hdrs){return new Promise((resolve,reject)=>{let done=false,t=setTimeout(()=>{if(!done){done=true;reject({ErrorMessage:'timeout'})}},12000);WsProxySDK.Command(method,params,query||{},data||{},hdrs||{},r=>{if(done)return;done=true;clearTimeout(t);r&&r.ErrorCode?reject(r):resolve(r&&r.Body||r)},e=>{if(done)return;done=true;clearTimeout(t);reject(e)})})}
  function connect(){if(socket&&socket.connected)return Promise.resolve();socket=WsProxySDK.ConnectWithFallback(PROXY,PROXY,{compress:true});return new Promise((ok,no)=>{let t=setTimeout(()=>no(Error('proxy connection timeout')),12000);socket.on('connect',()=>{clearTimeout(t);ok()});socket.on('connect_error',e=>{clearTimeout(t);no(e)})})}
  function firstStream(info){for(const list of [info&&info.StreamConfigList,info&&info.ChildStreamConfigList,info&&info.Streams])for(const s of list||[])if(s&&s.StreamName&&s.Protocol==='h5Wss')return s;return null}
  async function startFeed(){try{await connect();let s=await command('post',{langId:'en',partnerId:PARTNER,controller:'Application',method:'InitSession'},null,{Table:{TableId:TABLE},PlatformType:'0',PartnerDomain:'https://duel.com',PlayerIp:'127.0.0.1'},headers());guestSid=s.Token;controller=s.Table&&s.Table.GameControllerName;if(!guestSid||!controller)throw Error('table session unavailable');let info=await command('get',{langId:'en',partnerId:PARTNER,controller,method:'GetStartupInfo'},{tableId:TABLE},null,headers({sid:guestSid})),stream=firstStream(info);if(!stream)throw Error('no live stream returned');player=new NanoPlayer('video');await player.setup({source:{entries:[{index:0,label:'Duel table '+TABLE,h5live:{rtmp:{url:stream.RtmpUrl||'rtmp://bintu-play.nanocosmos.de:1935/play',streamname:stream.StreamName},server:H5,token:'',security:{}},hls:'',tag:'',bintu:{}}]},playback:{autoplay:true,automute:true,muted:true,faststart:true,latencyControlMode:'balancedadaptive',reconnect:{minDelay:1,maxDelay:3,delaySteps:2,maxRetries:30},timeouts:{connecting:12,loading:24}},style:{controls:false,width:'100%',height:'100%',interactive:false,scaling:'letterbox'},events:{onPlay:()=>state.textContent='Live · table '+TABLE,onError:e=>state.textContent='Feed error · '+(e.message||e.code||'retrying')}})}catch(e){state.textContent='Feed unavailable · '+(e.ErrorMessage||e.message||e)}}
  async function login(){let token=document.getElementById('token').value.trim();if(!/^[a-z0-9]{16,64}$/i.test(token)){auth.textContent='Enter a valid hexadecimal launch token.';return}auth.textContent='Authenticating…';try{await connect();let r=await command('post',{langId:'en',partnerId:PARTNER,controller:'Application',method:'InitSession'},null,{ClientCredentials:{Token:token,IsCashDesk:0},PlatformType:'0',PartnerDomain:'https://duel.com',PlayerIp:'127.0.0.1'},headers());if(!r||!r.Token)throw Error('no authenticated session returned');userSid=r.Token;userNick=r.NickName||(r.Player&&(r.Player.NickName||r.Player.UserName))||'player';auth.textContent='Connected as '+userNick;mountChat()}catch(e){userSid='';auth.textContent='Token rejected · '+(e.ErrorMessage||e.message||e)}}
  function mountChat(){if(chatHandle)try{chatHandle.destroy()}catch(e){}document.getElementById('chat').innerHTML='';chatHandle=StreamChat.mount(document.getElementById('chat'),{tableId:TABLE,label:'Table '+TABLE})}
  window.AGG={partnerId:()=>PARTNER,chatPartnerId:()=>PARTNER,command,headers,getSid:()=>guestSid,userSid:()=>userSid,userNick:()=>userNick,focusPanel:()=>{},selectedPanel:()=>null};
  document.getElementById('connect').addEventListener('click',login);document.getElementById('token').addEventListener('keydown',e=>{if(e.key==='Enter')login()});document.getElementById('sound').addEventListener('click',()=>{if(!player)return;try{player.unmute();player.setVolume(1);document.getElementById('sound').textContent='Sound on'}catch(e){}});
  startFeed().then(mountChat);
})();
